# src/paginas/__init__.py
from .resumen_ejecutivo import mostrar_resumen_ejecutivo
from .fuga_capital import mostrar_fuga_capital
from .crisis_logistica import mostrar_crisis_logistica
from .venta_invisible import mostrar_venta_invisible
from .diagnostico_fidelidad import mostrar_diagnostico_fidelidad
from .riesgo_operativo import mostrar_riesgo_operativo
from .salud_dato import mostrar_salud_datos